### ISSUE TITLE
nginx error

### ISSUE THREAD

**Issue by sutirath** [evgeniy-khist/letsencrypt-docker-compose#11]
nginx: [emerg] open() "/etc/nginx/vhosts/"mydomain".conf" failed (2: No such file or directory) in /etc/nginx/sites/"mydomain".conf:27
nginx_1    | Checking configuration for "mydomain"
nginx_1    | Waiting for Let's Encrypt certificates for "mydomain"
nginx_1    | 2022/05/28 07:48:28 [emerg] 1#1: open() "/etc/nginx/vhosts/"mydomain".conf" failed (2: No such file or directory) in /etc/nginx/sites/"mydomain"

**Comment by evgeniy-khist** [comment]
It looks like the problem is in double quotes `"` - `"mydomain"`.
Could you please share your `config.env` file?
What operating system do you use?
What version of Docker Compose?
Do you use `docker compose` plugin or `docker-compose` binary?

**Comment by sutirath** [comment]
### Before 
```
DOMAINS="mydomain"
CERTBOT_EMAILS="mydomain"
CERTBOT_TEST_CERT=1
CERTBOT_RSA_KEY_SIZE=4096
```

### After
```
DOMAINS=mydomain
CERTBOT_EMAILS=mydomain
CERTBOT_TEST_CERT=1
CERTBOT_RSA_KEY_SIZE=4096
```

it work but show new error
```
Domain: mydomain
certbot_1  |   Type:   unauthorized
certbot_1  |   Detail: 209.99.40.222: Invalid response from http://mydomain/.well-known/acme-challenge/binA6tKJqQmubNaKLL41Kttm5J4P_RkWcelFwesSV6E: 404
```

**Comment by evgeniy-khist** [comment]
`DOMAINS=mydomain` must be a valid domain that you own and `CERTBOT_EMAILS=mydomain` must be a valid email.
If you buy the domain `siturath.com` then the config will be:
```bash
DOMAINS=siturath.com
CERTBOT_EMAILS=siturath@gmail.com
```

**Comment by sutirath** [comment]
i have set

mydomail = takeco.online

```
DOMAINS="customer.takeco.online"
CERTBOT_EMAILS="info@takeco.online"
CERTBOT_TEST_CERT=1
CERTBOT_RSA_KEY_SIZE=4096
```

**Comment by evgeniy-khist** [comment]
And does it work now? What is the problem in logs?

**Comment by evgeniy-khist** [comment]
Anyway, thanks for raising the issue. I updated the README regarding the usage of double quotes - https://github.com/evgeniy-khist/letsencrypt-docker-compose/commit/d102ab1de3a1599b3ee067da4a4dc6f277a19b2d
