### ISSUE TITLE
scripts don't handle the double-quotes for $DOMAINS

### ISSUE THREAD

**Issue by kryptojenix** [evgeniy-khist/letsencrypt-docker-compose#13]
the definition in config.env requires multiple domains to be within double quotes. The scripts don't remove them before iterating; the scripts get quotes in the paths
"site1.com site2.com" gives us /var/html/"site1.conf

My hack to fix it:
### certbot.sh
```
fixed_domains=$(echo $DOMAINS | sed  's/"//g')
domain_list=($fixed_domains)
# domain_list=($DOMAINS)
```
### nginx.sh
```
fixed_domains=$(echo $DOMAINS | sed  's/"//g')
for domain in $fixed_domains; do

```
thanks for your work

**Comment by evgeniy-khist** [comment]
@kryptojenix , thanks for reporting this issue. Nice workaround. On what OS and Docker version do you run the solution?

**Comment by kryptojenix** [comment]
OS is Debian 11
Docker version 20.10.5+dfsg1, build 55c4c88
docker-compose version 1.25.0, build unknown
and version: "3.7" in my docker-compose.yml
