### ISSUE TITLE
certbot and nginx waiting for eachother

### ISSUE THREAD

**Issue by NiiWiiCamo** [evgeniy-khist/letsencrypt-docker-compose#18]
Just created everything based on the directions, nginx_1 is periodically printing
Waiting for Let's Encrypt certificates for [mydomain]
and certbot_1 is printing
Waiting for nginx to start...
every now and then.

Did I mess up the config anywhere?

**Comment by evgeniy-khist** [comment]
@NiiWiiCamo , I've just checked the config and it works for my domain.
Maybe, you have a mistake in the configuration.
Please, share the full Nginx and Certbot containers logs.

**Comment by NiiWiiCamo** [comment]
As it turned out I had the same issues with the dockerized version of letsencrypt by itself.
Have switched to native install for now, need to do troubleshooting on my own here.

Thanks for the fast response!
