### ISSUE TITLE
Removing a domain

### ISSUE THREAD

**Issue by verlor** [evgeniy-khist/letsencrypt-docker-compose#22]
Hi folks!

Thank you for sharing this amazing project. 

When trying to remove a domain from my server I realized there was no explanation within the `README` file. It may be obvious for some people, but I think it would be nice to add a section to specify how to remove a domain. Something like :

## Removing a domain name from a running solution

Remove the `.conf` file from `vhost`

Remove the domain name from [config.env](https://github.com/evgeniy-khist/letsencrypt-docker-compose/blob/master/config.env)

```bash
docker compose down
docker volume rm nginx_conf
docker volume create --name=nginx_conf
docker compose up -d
```

**Comment by verlor** [comment]
Actually went ahead an made a pull request #23.  Please let me know if there's any feedback. Thank you

**Comment by evgeniy-khist** [comment]
@verlor, I merged your PR. Thanks you for contributing!
