### ISSUE TITLE
All domains will apear offline when one backend container is offline at startup of nginx container

### ISSUE THREAD

**Issue by Humphreybas** [evgeniy-khist/letsencrypt-docker-compose#26]
Nice work, it worked good!

Just one question.
Imagine, you have a server with two applications, one 'live production' version of a project and one development version of the same project. Each reachable by their own domain:
dev.myproject.com
live.myproject.com

Now when I start everything together (two backends for the application and one time letsencrypt-docker-compose) everything is nice.
When I stop the dev container (for some work on the docker config or whatever), the live application will still be reachable, great.
But then when I have the dev container stopped, and I restart the whole server (or the nginx container to be specific) then the nginx will not start anymore because it cannot find the development backend. It will fail with:

```
nginx_1    | 2022/11/12 09:50:55 [emerg] 1#1: host not found in upstream "dev_backend" in /etc/nginx/vhosts/dev.myproject.com.conf:6
nginx_1    | nginx: [emerg] host not found in upstream "dev_backend" in /etc/nginx/vhosts/dev.myproject.com.conf:6

```

Is there any way to have nginx start anyway with all backends that are available?

**Comment by evgeniy-khist** [comment]
Hi! Interesting case. I will try to find solution.

**Comment by Humphreybas** [comment]
Thanks! I was curious if this was a general nginx thing, so I googled that just now, and it is. I found this [blog post](https://sandro-keil.de/blog/let-nginx-start-if-upstream-host-is-unavailable-or-down/).
