### ISSUE TITLE
Anyway to loop over a list in nginx?

### ISSUE THREAD

**Issue by formula1** [evgeniy-khist/letsencrypt-docker-compose#3]
This is a great example but I want a more generic version. I'm currently rewriting it in nodejs but looking at the simplicity and elegance of nginx I'm somewhat disappointed I'm attempting to rewrite it. Nonetheless, I don't particularly want to have to add new servers everytime I want to update the conf. I'd prefer it loop yml file or something like that.

**What I thought you did great**

- Allow the person to set multiple domains
- Allow the person to set multiple emails
- Handling the acme challenge
- redirecting all other traffic to https
- You're including both the toplevel domain and it's www subdomain for both nginx and the certbot
- You've got a nice little cron job going in the background

**To Make it more Generic**

- How do you load an array into nginx?
  - [I see an example of looping over a list](http://nginx.org/en/docs/dev/development_guide.html#list)
  - But How do you load it in from environment variables or a file?
  - [This seems interesting](https://unit.nginx.org/) but it's a little hard to understand for me
- dynamically creating the file may work but that seems a bit rediculous
  - [This looks promising though](https://www.npmjs.com/package/@webantic/nginx-config-parser)
- creating a bunch of child processes listening on the same port but then I would have a proxy server in front of my proxy server

**Some features I am attempting to implement in nodejs**

- *Unlimited* domains (To safe numbers and restricted by hardware)
- *Unlimited* subdomains per domain (To safe numbers and restricted by hardware)
  - catches invalid subdomains like bad wildcards or empty parts
  - does not catch things like me.formula1.com vs *.formula1.com. No need for the me.formula1.com since the wildcard is catching it
- Default email parameter
  - this way the user doesn't have to set an email per virtual host
- forwarding the request to another server instead of serving static files
  - I don't know what a single server is going to be. Perhaps its just static files. But that can be it's own docker container
- Ability to manually run it as a command and manually set certain args to override the config file
  - https://www.npmjs.com/package/commander

**Probably Going to ignore some things**

- Uppercase vs Lowercase - just sounds like a pain in the butt. I suppose I could just make everything lowercase though

I was going to setup a command to restart the server but I realized the cronjob will probably be fine

But I am a bit dissappointed though. Nginx seems like such a useful tool and nice on the eyes as well. And while you can do some amazing things in node, I'd prefer to have a simple configuration rather than big project I have to maintain.

**Comment by formula1** [comment]
Example Config

```typescript

const DEFAULT_FORWARD_ORIGIN = {
  protocol: "http:",
  hostname: "localhost",
  port: 8080,
}
// if number, replace the port
// if string, replace the defaults with the parsed url
// if a partial, replace the defaults with the ones found in the partial
type ForwardOrigin = number | string | Partial<{
  protocol: "http:" | "https:",
  hostname: string,
  port: number
}>

type ServerConfig = {
  // if specified as an argument, resolves relative to cwd otherwise resolves relative to location of the config file
  "certRootPath": string,

  // if specified as an argument, resolves relative to cwd otherwise resolves relative to location of the config file
  "acmeRootPath: string,

  // Amount of time to wait for the forwarded server to respond
  "timeout": number,

  // default email address
  "email": string,
  
  // how to handle requests that don't have certificates
  "defaultConfig": {
      // if none - don't refuse anything
      // if based on an ip address, refuse it
      // if based on a unknown host, refuse it
      // otherwise refuse all
      refuse: "none" | "ip" | "hosts" | "all"

      // where to forward all unknown requests to
      forward: ForwardOrigin
    }

  "vhosts": Array<{
    // the base hostname for the http server and the certbot
    "hostname": string,
    
    // The email that will override the default
    email?: string,
    
    // Where to forward the request to
    forward: ForwardOrigin
    
    // a list of subdomains that the https server will handle and the certbot will handle when it requests certs
    subdomains?: Array<string>
  }>
}

```

**Comment by evgeniy-khist** [comment]
If you are thinking about implementing a Node.js solution for obtaining Let's Encrypt certificates on the fly and later automatically renewing them, then take a look at this Node.js library first: https://www.npmjs.com/package/greenlock

**Comment by formula1** [comment]
This looks AMAZING! AHHHH! I wrote all this code for nothing.

Whatever, it's good practice and if anyone finds it I'll point them towards greenlock

**Comment by formula1** [comment]
https://git.rootprojects.org/root/greenlock-express.js
https://git.rootprojects.org/root/greenlock-express.js/src/branch/master/examples/http-proxy/server.js

Looks like theres still ore code to be done but I think this still saves me a bunch of time
