### ISSUE TITLE
Cron - auto renewal fails

### ISSUE THREAD

**Issue by YogiBear52** [evgeniy-khist/letsencrypt-docker-compose#31]
Hello,
3 months ago, I installed Cerbot using this repo.
Everything worked fine; the dev and prod certificates were produced, and my website got to work with a good-working certificate.

3 month later.. The "cron" service tried to renew the certificate and failed with these logs: (I replaced the real domain with <DOMAIN> and the real IP with <IP>)
```
cron_1     | Renewing Let's Encrypt Certificates... (Wed Jan 11 02:00:00 UTC 2023)
cron_1     | 
cron_1     | - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
cron_1     | Processing /etc/letsencrypt/renewal/<DOMAIN>.conf
cron_1     | - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
cron_1     | Renewing an existing certificate for <DOMAIN> and www.<DOMAIN>
cron_1     | 
cron_1     | Certbot failed to authenticate some domains (authenticator: webroot). The Certificate Authority reported these problems:
cron_1     |   Domain: <DOMAIN>
cron_1     |   Type:   unauthorized
cron_1     |   Detail: <IP>: Invalid response from http://<DOMAIN>/.well-known/acme-challenge/ZCAkhfiArMRJF7uLvXSEftoDzF4eN24_TXrolUxiv2I: 404
cron_1     | 
cron_1     |   Domain: www.<DOMAIN>
cron_1     |   Type:   unauthorized
cron_1     |   Detail: <IP>: Invalid response from http://www.<DOMAIN>/.well-known/acme-challenge/h2aqQxpCb11Pw5qoDa1J-pZ6biPTECxXtPs_LkbCt_M: 404
cron_1     | 
cron_1     | Hint: The Certificate Authority failed to download the temporary challenge files created by Certbot. Ensure that the listed domains serve their content from the provided --webroot-path/-w and that files created there can be downloaded from the internet.
cron_1     | 
cron_1     | Saving debug log to /var/log/letsencrypt/letsencrypt.log
cron_1     | Failed to renew certificate <DOMAIN> with error: Some challenges have failed.
cron_1     | 
cron_1     | - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
cron_1     | All renewals failed. The following certificates could not be renewed:
cron_1     |   /etc/letsencrypt/live/<DOMAIN>/fullchain.pem (failure)
cron_1     | - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
cron_1     | 1 renew failure(s), 0 parse failure(s)
cron_1     | Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
cron_1     | Reloading Nginx configuration
cron_1     | service "nginx" is not running container #1
cron_1     | run-parts: /etc/periodic/daily/renew_certs: exit status 1
cron_1     | Ren
```

Basically, it says that when requesting .well-known/acme-challenge/h2aqQxpCb11Pw5qoDa1J-pZ6biPTECxXtPs_LkbCt_M it gets a 404.
When I was checking the .well-known/acme-challenge/<DOMAIN>/ it did seem empty.
So I manually tried to add a file there, and it did succeed getting it with curl/postman.

Just to make it work again, I deleted all the volumes and reran the project again. But it will probably happen again every 3 months.

Any idea?
** I am using the latest version of this code

Thanks!

**Comment by evgeniy-khist** [comment]
Hi! I haven't heard about such issue before.
Do you have possibility to troubleshoot this problem s little?
Cron container executes a simple command: `docker compose run --rm --no-TTY --entrypoint certbot certbot renew --no-random-sleep-on-renew` (https://github.com/evgeniy-khist/letsencrypt-docker-compose/blob/876034c0e239bf409c562c5b4266c1bc61062578/cron/renew_certs.sh#L5). This command can be executed from the host machine.
If manually executed command will also fail with the same error, it means the problem is reproducible.
If possible, switch back to staging certificates by setting `CERTBOT_TEST_CERT=1` in `config.env`.

**Comment by YogiBear52** [comment]
Hey, 
I have changed the setting `CERTBOT_TEST_CERT=1`. Then ran it.
Since I restarted the whole process few days ago just to make it work, it throws 'The following certificates are not due for renewal yet'. Is there a way to make it renew before the due date?
Thanks!

```
Processing /etc/letsencrypt/renewal/<DOMAIN>.conf
Certificate not yet due for renewal

The following certificates are not due for renewal yet:
  /etc/letsencrypt/live/<DOMAIN>/fullchain.pem expires on 2023-04-12 (skipped)
No renewals were attempted.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
```

**Comment by evgeniy-khist** [comment]
I'm sorry, I forgot to mention about force renewal.
The command should be

```bash
docker compose run --rm --no-TTY --entrypoint certbot certbot renew --no-random-sleep-on-renew --force-renew
```

The `--force-renew` flag tells Certbot to request a new certificate with the same domains as an existing certificate.

**Comment by YogiBear52** [comment]
I got a success response! :)
```
Congratulations, all renewals succeeded: 
  /etc/letsencrypt/live/<DOMAIN>/fullchain.pem (success)
```

Does the certificate issue time suppose to change immediately? Because it still refers to the previous date, when I issued it again few days ago.

**Comment by evgeniy-khist** [comment]
So, it looks like the issue is floating and at least staging certificates can be renewed.
Please, try one time to renew production certificates:

- `CERTBOT_TEST_CERT=0`
- `docker compose run --rm --no-TTY --entrypoint certbot certbot renew --no-random-sleep-on-renew --force-renew`

> Does the certificate issue time suppose to change immediately?

Renewed certificates are not loaded by Nginx. You need to reload Nginx:

`docker compose exec --no-TTY nginx nginx -s reload`

**Comment by YogiBear52** [comment]
It works.
Also while browsing, the new certificate is loaded and works fine.

Let's hope it won't happen again close to the due-time

Thanks
