### ISSUE TITLE
Support HTTP2 / Support IPv6

### ISSUE THREAD

**Issue by lakano** [evgeniy-khist/letsencrypt-docker-compose#32]
Hi,

Thank you for your works, it's save time and it's cleaner!

1) There is a reason to not add per default HTTP2 support for TLS ?

2) Your nginx default configuration doesn't support IPv6
I've noticed that on testing the TLS grade on SSLLabs test service.
So, I wanted to add IPv6 support on nginx/site.conf.tpl : 

Before:

> (...)
>     listen 80;
> (...)
>     listen 443 ssl;
> (...)

After

> (...)
>     listen 80;
>     listen [::]:80;
> (...)
>     listen 443 ssl http2;
>     listen [::]:443 ssl http2;
> (...)

The syntax is ok, I've done a reload without success, and so a total down/up of the services, but doesn't seems to be enough.
May be when the TLS certificates are done per Let's Encrypt it's only done on IPv4 if it's not respond on IPv6 and it's now too late to redo it, or may be it's not related to Let's Encrypt and more related to the nginx/docker config?

If you have any clue to help me to add support to IPv6 of my TLS certs. 
Thank you!

**Comment by evgeniy-khist** [comment]
Hi, @lakano 

listen 80;
listen [::]:80;



listen 443 ssl http2;
listen [::]:443 ssl http2;

**Comment by evgeniy-khist** [comment]
Hi, @lakano 
Indeed, IPv6 and HTTP/2 support should be added.
The following configuration of [site.conf.tpl](https://github.com/evgeniy-khist/letsencrypt-docker-compose/blob/master/nginx/site.conf.tpl) looks correct:
```
listen 80;
listen [::]:80;

listen 443 ssl http2;
listen [::]:443 ssl http2;
```

And then restart `docker compose restart nginx`.

Have you configured AAAA DNS record? Or only A DNS record?

Do you any error in the Nginx logs?

Try running `docker compose exec nginx netstat -anlp`. Does the output contain any `tcp6` entry?

Have you read https://letsencrypt.org/docs/ipv6-support/ ?

**Comment by lakano** [comment]
Yes I had my AAAA records, it's why SSLLabs try it, but I think my ISP internet box isn't smart enough to also forward IPv6 trafic unfortunatly!

**Comment by evgeniy-khist** [comment]
Anyway, I will add IPv6 and HTTP/2 support to the project to work out of the box.
