### ISSUE TITLE
Three of the created files owned by root?

### ISSUE THREAD

**Issue by tka85** [evgeniy-khist/letsencrypt-docker-compose#37]
After running `docker compose run --rm cli` I noticed that three of the generated files are owned by root:

```
./nginx-conf/conf.d/amazonsnitch.com.conf
./nginx-conf/nginx.conf
./config.json
```

Was it something I did? If not, shouldn't they all be editable? It's mentioned in the docs for example to edit `./nginx-conf/nginx.conf` to make manual adjustmants to Nginx.

**Comment by evgeniy-khist** [comment]
@tka85 , please check the new README section [Running Docker containers as a non-root user](https://github.com/evgeniy-khist/letsencrypt-docker-compose#running-docker-containers-as-a-non-root-user) for the solution.
