### ISSUE TITLE
Add a domain to running config

### ISSUE THREAD

**Issue by CmdLnInt** [evgeniy-khist/letsencrypt-docker-compose#4]
I have setup a dual domain config according to your example. I would like to add a third domain now and I am not sure how to do that without breaking the running domains. How would I add an extra domain to a running config?

**Comment by evgeniy-khist** [comment]
I will also start working on a new version that will support adding new domains easily without much manual steps.

**Comment by CmdLnInt** [comment]
This doesn't seem to work.

I get the following message:

```
Obtaining the certificate for test3.devcomanda.com
Requesting a certificate for test3.devcomanda.com and www.test3.devcomanda.com

Certbot failed to authenticate some domains (authenticator: webroot). The Certificate Authority reported these problems:
  Domain: test3.devcomanda.com
  Type:   unauthorized
  Detail: Invalid response from http://test3.devcomanda.com/.well-known/acme-challenge/qbCwheYSviVsndkGkvFvU3YtHgOeefRlQJvITsPSlLA [x.x.x.x]: "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body>\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx/1.17.10</c"
```
As far as I can tell /var/www/certbot/test3.devcomanda.com does not exist in nginx container.

**Comment by evgeniy-khist** [comment]
Just want to make sure, that instead of `test3.devcomanda.com` you are using your real domain.
`/var/www/certbot/test3.devcomanda.com` should exist if you added volume `test3_devcomanda_com_certbot` as I've described above.
Anyway, I will improve and simplify the solution in a few days.

**Comment by CmdLnInt** [comment]
I am using my own domain names and I have added the volume to docker-compose.yml. Maybe i need to add `--build` ie
`docker-compose up --build -d`
Will that break my running config?

**Comment by CmdLnInt** [comment]
Adding `--build` causes this message

`[emerg] 1#1: cannot load certificate "/etc/letsencrypt/live/test3.devcomanda.com/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/test3.devcomanda.com/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)`

**Comment by evgeniy-khist** [comment]
Could you attach the full log of the certbot container?

**Comment by CmdLnInt** [comment]
certbot logs only have this

```
Waiting for nginx to start...
nc: bad address 'nginx'
Waiting for nginx to start...
nc: bad address 'nginx'
Waiting for nginx to start...
nc: bad address 'nginx'
Waiting for nginx to start...
Waiting for nginx to start...
nc: bad address 'nginx'
nc: bad address 'nginx'
Waiting for nginx to start...
nc: bad address 'nginx'
Waiting for nginx to start...
nc: bad address 'nginx'
Waiting for nginx to start...
nc: bad address 'nginx'
Waiting for nginx to start...
nc: bad address 'nginx'
Waiting for nginx to start...
Waiting for nginx to start...
nc: bad address 'nginx'
Waiting for nginx to start...
nc: bad address 'nginx'
Waiting for nginx to start...
nc: bad address 'nginx'
Waiting for nginx to start...
```
nginx logs have this
```
Switching Nginx to use Let's Encrypt certificate for test1.devcomanda.com
Switching Nginx to use Let's Encrypt certificate for test2.devcomanda.com
Switching Nginx to use Let's Encrypt certificate for test3.devcomanda.com
2022/02/25 08:04:28 [emerg] 1#1: cannot load certificate "/etc/letsencrypt/live/test3.devcomanda.com/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/test3.devcomanda.com/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/test3.devcomanda.com/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/test3.devcomanda.com/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
```

**Comment by CmdLnInt** [comment]
My config seems correct because it all works as expected once I do
```
docker-compose down
docker container purge
docker volume purge
docker volume create --name=devcomanda_nginx_ssl
docker volume create --name=devcomanda_certbot_certs
docker-compose up --build
```

**Comment by evgeniy-khist** [comment]
OK, clear. I will try to fix it. Thanks for sharing the logs.

**Comment by evgeniy-khist** [comment]
@CmdLnInt , finally I've finished with the fix and updated the documentation: https://github.com/evgeniy-khist/letsencrypt-docker-compose/#df4dbc9f0317b0524962bc438bed627b
But the initial setup has also changed a bit: https://github.com/evgeniy-khist/letsencrypt-docker-compose/#6641666d7bc2748bab0ac80cdec3a2a3
