### ISSUE TITLE
Changes to site.conf.tpl is not propergated

### ISSUE THREAD

**Issue by groskopf** [evgeniy-khist/letsencrypt-docker-compose#9]
I have experienced issues with trying alternative nginx configuration via changes to site.conf.tpl. This was due to the fact that nginx.sh is only creating new /etc/nginx/sites/$domain.conf if it does not allready exist. This means that updated are not propergated to the docker volume.

**Comment by evgeniy-khist** [comment]
Hi @groskopf
Good point. I will do an improvement to allow updating the virtual host configuration.

**Comment by evgeniy-khist** [comment]
@groskopf, please update the repo and check this sections:
- https://github.com/evgeniy-khist/letsencrypt-docker-compose#3414177b596079dbf39b1b7fa10234c6
- https://github.com/evgeniy-khist/letsencrypt-docker-compose#45a36b34f024f33bed82349e9096051a
